AllCops:
  Exclude:
    - '.git-hooks/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/bundle/**/*'
    - 'config/environments/*'

Style/ModuleFunction:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
